version: '3.8'

# Set Variables: TS_AUTH, TS_CERT_DOMAIN, MINIO_ROOT_USER, MINIO_ROOT_PASSWORD, WEAVIATE_ORGIN
# Configuration Files: TS_SERVE_CONFIG 

services:
  tailscale-aiops:
    image: tailscale/tailscale:latest
    container_name: tailscale-aiops
    hostname: tailscale-minio-python # The Tailnet node will be named this for use with MagicDNS
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ${PWD}/tailscale-aiops/state:/var/lib/tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/tailscale/minio.json
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    depends_on:
      - tailscale
    network_mode: service:tailscale-aiops

  python-app:
    build: ./app
    depends_on:
      - tailscale
      - minio
    network_mode: service:tailscale-aiops

volumes:
  tailscale_data:
    driver: local
  minio_data:
    driver: local

networks:
  app_network:
    driver: bridge 