name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Compose
        run: |
          echo "TS_AUTHKEY=${{ secrets.TS_AUTHKEY }}" >> $GITHUB_ENV
          echo "MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}" >> $GITHUB_ENV
          echo "MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}" >> $GITHUB_ENV
          
      - name: Run Docker Compose
        run: docker-compose -f docker-compose.yaml up -d
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
          MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
          MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
